import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786474996311 implements MigrationInterface {
    name = 'InitialSchema1786474996311'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "persona" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id_persona" BIGSERIAL NOT NULL, "ci" character varying(32) NOT NULL, "nombre" character varying(128) NOT NULL, "paterno" character varying(128), "materno" character varying(128), "fecha_nacimiento" date, "genero" character varying(1), "celular" character varying(32), "email" character varying(255), "direccion" character varying(512), "foto" character varying(1024), CONSTRAINT "UQ_5cd57db9cc1b133cacb180b29e5" UNIQUE ("ci"), CONSTRAINT "PK_a5b8321cce9bc11ca8931257ca3" PRIMARY KEY ("id_persona"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5cd57db9cc1b133cacb180b29e" ON "persona" ("ci") `);
        await queryRunner.query(`CREATE INDEX "IDX_86ae2f9d6da4482363f832340b" ON "persona" ("email") `);
        await queryRunner.query(`CREATE TABLE "rol" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" SMALLSERIAL NOT NULL, "codigo" character varying(64) NOT NULL, "descripcion" character varying(255) NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_59960bb0e72a21e5c347566fb4a" UNIQUE ("codigo"), CONSTRAINT "PK_c93a22388638fac311781c7f2dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuario_rol" ("usuario_id" bigint NOT NULL, "rol_id" smallint NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_40b321ebb932d588934043a2639" PRIMARY KEY ("usuario_id", "rol_id"))`);
        await queryRunner.query(`CREATE TABLE "usuario" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "id_persona" bigint, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "nombre" character varying(255), "denomination" character varying(100), "address" character varying(255), "enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_2863682842e688ca198eb25c124" UNIQUE ("email"), CONSTRAINT "PK_a56c58e5cabaa04fb2c98d2d7e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auditoria_cambio" ("id" BIGSERIAL NOT NULL, "tabla_afectada" character varying(128) NOT NULL, "id_registro_original" bigint, "accion" character varying(16) NOT NULL, "datos_anteriores" jsonb, "datos_nuevos" jsonb, "id_usuario" bigint, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c7971c94d15e64562557fadbfde" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "catalogo_tipo" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" SMALLSERIAL NOT NULL, "codigo" character varying(1) NOT NULL, "descripcion" character varying(128) NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_9d77cd5c1fbcbaf85037262072f" UNIQUE ("codigo"), CONSTRAINT "PK_206a7ae8a0f03431f6b0628684f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "catalogo_nivel" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" SMALLSERIAL NOT NULL, "codigo" character varying(1) NOT NULL, "descripcion" character varying(128) NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_a11a77d00385ee69bfc4b86eaa9" UNIQUE ("codigo"), CONSTRAINT "PK_2525ce16bf5a82bfa73e54a6204" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "catalogo_relacion" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" SMALLSERIAL NOT NULL, "codigo" character varying(1) NOT NULL, "descripcion" character varying(128) NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_3c9142c7e7e9d6cff083282af5d" UNIQUE ("codigo"), CONSTRAINT "PK_4eba1965886519770178a10a8a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipo_unidad" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" SMALLSERIAL NOT NULL, "codigo" character varying(32) NOT NULL, "descripcion" character varying(255) NOT NULL, "peso" integer NOT NULL DEFAULT '0', "color" character varying(10), "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_24534c72f1dd8a7db10f2b66d53" UNIQUE ("codigo"), CONSTRAINT "PK_ad5ee5f4f96ea97b00d78fd40d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unidad_funcion" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "unidad_id" bigint NOT NULL, "orden" integer NOT NULL DEFAULT '1', "funcion" character varying(1024) NOT NULL, "base_legal" character varying(1024), CONSTRAINT "PK_0fdb3026b42cf9482bb05d0021f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unidad_relacion_externa" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "unidad_id" bigint NOT NULL, "descripcion" character varying(1024) NOT NULL, CONSTRAINT "PK_efa07d599983198fc5638fff59f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unidad_relacion_interna" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "unidad_id" bigint NOT NULL, "relacionada_id" bigint NOT NULL, "tipo" character varying(32), CONSTRAINT "UQ_fe57fcd7b6f1da365b2d0f85493" UNIQUE ("unidad_id", "relacionada_id"), CONSTRAINT "PK_659b7f4261f95428f66c89b92a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unidad" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "codigo" character varying(64) NOT NULL, "sigla" character varying(32) NOT NULL, "nombre" character varying(255) NOT NULL, "parent_id" bigint, "tipo_unidad_id" smallint NOT NULL, "tipo_id" smallint NOT NULL, "nivel_id" smallint NOT NULL, "relacion_id" smallint NOT NULL, "oficial" boolean NOT NULL DEFAULT false, "objetivo" text, "base_legal" text, "res_creacion" character varying(512), "fec_creacion" date, "created_by" bigint, "updated_by" bigint, CONSTRAINT "UQ_861ec82ab1c13cb0a2ee94d10a1" UNIQUE ("codigo"), CONSTRAINT "UQ_07cd99340fb171274e5bfed5963" UNIQUE ("sigla"), CONSTRAINT "PK_3f087c90fe8ce6bafe8f8af6779" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_861ec82ab1c13cb0a2ee94d10a" ON "unidad" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_07cd99340fb171274e5bfed596" ON "unidad" ("sigla") `);
        await queryRunner.query(`CREATE TABLE "unidad_jerarquia_hist" ("id" BIGSERIAL NOT NULL, "unidad_id" bigint NOT NULL, "parent_id_anterior" bigint, "parent_id_nuevo" bigint, "razon" character varying(512), "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "changed_by" bigint, CONSTRAINT "PK_85850319e359419564156329797" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unidad_dependencia_funcional" ("unidad_id" bigint NOT NULL, "dependencia_id" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_053eaf1defc9cdaa0e42ad30c43" PRIMARY KEY ("unidad_id", "dependencia_id"))`);
        await queryRunner.query(`ALTER TABLE "unidad_dependencia_funcional" ADD CONSTRAINT "CHK_unidad_dependencia_diferente" CHECK ("unidad_id" <> "dependencia_id")`);
        await queryRunner.query(`CREATE TABLE "cargo" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "codigo" character varying(64), "nombre" character varying(255) NOT NULL, "descripcion" character varying(512), "parent_id" bigint, "unico_en_unidad" boolean NOT NULL DEFAULT false, "activo" boolean NOT NULL DEFAULT true, "created_by" bigint, "updated_by" bigint, CONSTRAINT "UQ_9467bfa162648a8bb148a68cbb2" UNIQUE ("codigo"), CONSTRAINT "PK_1af8b2a790f35aedbe7e3da4199" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cargo_nivel" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" SMALLSERIAL NOT NULL, "letra" character varying(8) NOT NULL, "nombre" character varying(128) NOT NULL, "descripcion" character varying(512), "orden" smallint NOT NULL, "activo" boolean NOT NULL DEFAULT true, "created_by" bigint, "updated_by" bigint, CONSTRAINT "UQ_d30b75f922d3ee67d6b0df76218" UNIQUE ("letra"), CONSTRAINT "PK_2c0729d27c29836458ebae33cb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d30b75f922d3ee67d6b0df7621" ON "cargo_nivel" ("letra") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5220df3d12d0ed70f587470e3" ON "cargo_nivel" ("orden") `);
        await queryRunner.query(`CREATE TABLE "cargo_unidad" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "cargo_id" bigint NOT NULL, "unidad_id" bigint NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_be300a4ad40515510434d76c455" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d4c270f3561571dede3a9b181" ON "cargo_unidad" ("unidad_id", "cargo_id") `);
        await queryRunner.query(`CREATE TABLE "cargo_jerarquia_hist" ("id" BIGSERIAL NOT NULL, "cargo_id" bigint NOT NULL, "parent_id_anterior" bigint, "parent_id_nuevo" bigint, "razon" character varying(512), "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "changed_by" bigint, CONSTRAINT "PK_3a1c3b321cf6e7bb7a8e1cac7ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "asignacion_cargo" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "id" BIGSERIAL NOT NULL, "id_persona" bigint NOT NULL, "cargo_id" bigint NOT NULL, "unidad_id" bigint NOT NULL, "cargo_nivel_id" smallint NOT NULL, "fecha_inicio" date NOT NULL, "fecha_fin" date, "activo" boolean NOT NULL DEFAULT true, "created_by" bigint, "updated_by" bigint, CONSTRAINT "PK_6383528d1c1a25fa35181f66561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66ad3bd27dca1daec5447228d0" ON "asignacion_cargo" ("unidad_id", "cargo_id") `);
        await queryRunner.query(`CREATE TABLE "asignacion_cargo_hist" ("id" BIGSERIAL NOT NULL, "asignacion_cargo_id" bigint NOT NULL, "cargo_nivel_id_anterior" smallint, "cargo_nivel_id_nuevo" smallint, "cargo_id_anterior" bigint, "cargo_id_nuevo" bigint, "unidad_id_anterior" bigint, "unidad_id_nuevo" bigint, "razon" character varying(512), "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "changed_by" bigint, CONSTRAINT "PK_c2b882900b503a7902ee4f3e219" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_29e9a9079c7ba01c1b301cf5555" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_ac8911cd54a61461c9926541401" FOREIGN KEY ("rol_id") REFERENCES "rol"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_1fbc7de91b8e96937ed27739e8f" FOREIGN KEY ("id_persona") REFERENCES "persona"("id_persona") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auditoria_cambio" ADD CONSTRAINT "FK_071d2676e20d33907f9dfd35b18" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_funcion" ADD CONSTRAINT "FK_469e4b9d573cdccb7cb117a924d" FOREIGN KEY ("unidad_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_relacion_externa" ADD CONSTRAINT "FK_2651ddf83eab297d6c9f88250a6" FOREIGN KEY ("unidad_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_relacion_interna" ADD CONSTRAINT "FK_11e015ea5591f1361f29eb86bb4" FOREIGN KEY ("unidad_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_relacion_interna" ADD CONSTRAINT "FK_d931058846fe3338ccf4902b4fc" FOREIGN KEY ("relacionada_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad" ADD CONSTRAINT "FK_10ac2cffa223556cf74dc141621" FOREIGN KEY ("parent_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad" ADD CONSTRAINT "FK_347f835cad56196221bea29b572" FOREIGN KEY ("tipo_unidad_id") REFERENCES "tipo_unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad" ADD CONSTRAINT "FK_ff4bf80818c0aa6e5486e1ab81d" FOREIGN KEY ("tipo_id") REFERENCES "catalogo_tipo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad" ADD CONSTRAINT "FK_5c52057af4061c6fb9baba16e12" FOREIGN KEY ("nivel_id") REFERENCES "catalogo_nivel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad" ADD CONSTRAINT "FK_94844a42a53e0a70efd65763d35" FOREIGN KEY ("relacion_id") REFERENCES "catalogo_relacion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad" ADD CONSTRAINT "FK_13a95ae8387dce63b0a542a9cdb" FOREIGN KEY ("created_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad" ADD CONSTRAINT "FK_c9ddfa456508681b5b2776b9b00" FOREIGN KEY ("updated_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" ADD CONSTRAINT "FK_277ae503a43eb5a218a3b068248" FOREIGN KEY ("unidad_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" ADD CONSTRAINT "FK_87c1ca734b13a8c5abbf0ee7076" FOREIGN KEY ("parent_id_anterior") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" ADD CONSTRAINT "FK_3189e3ae4d0abc8be343e98833f" FOREIGN KEY ("parent_id_nuevo") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" ADD CONSTRAINT "FK_d6f6f4e40d731848abfb6439138" FOREIGN KEY ("changed_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_dependencia_funcional" ADD CONSTRAINT "FK_1f3c749e081a5b26ea2f40d759e" FOREIGN KEY ("unidad_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidad_dependencia_funcional" ADD CONSTRAINT "FK_1335f38e53860a0875e4e5bb5c4" FOREIGN KEY ("dependencia_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_fa5bec4729251d55f99d694df35" FOREIGN KEY ("parent_id") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_d450c004048c0d34b06c6a3ee31" FOREIGN KEY ("created_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_23819fac1eadcc0723ecfa776ec" FOREIGN KEY ("updated_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_nivel" ADD CONSTRAINT "FK_b49abae8123146baa3a442d85b5" FOREIGN KEY ("created_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_nivel" ADD CONSTRAINT "FK_5236f3b0b7df382a9e31d5e8bbc" FOREIGN KEY ("updated_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_unidad" ADD CONSTRAINT "FK_3587e73fd858b4b1481c365f12c" FOREIGN KEY ("cargo_id") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_unidad" ADD CONSTRAINT "FK_b504f6ad081e70588e1603204b2" FOREIGN KEY ("unidad_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" ADD CONSTRAINT "FK_7c4fef8d47aad3a04af9903c691" FOREIGN KEY ("cargo_id") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" ADD CONSTRAINT "FK_4372c3a2d85776b49f0be9ce9cd" FOREIGN KEY ("parent_id_anterior") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" ADD CONSTRAINT "FK_72224b7331d73d4b400374deda9" FOREIGN KEY ("parent_id_nuevo") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" ADD CONSTRAINT "FK_af6d351da6c6de38c178a5810e4" FOREIGN KEY ("changed_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" ADD CONSTRAINT "FK_9eacdb795f7702bee3d5d13f619" FOREIGN KEY ("id_persona") REFERENCES "persona"("id_persona") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" ADD CONSTRAINT "FK_b3b847b97b58bd340c4148136b9" FOREIGN KEY ("cargo_id") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" ADD CONSTRAINT "FK_b3d2a1b7617953e4ec7ad2b4404" FOREIGN KEY ("unidad_id") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" ADD CONSTRAINT "FK_7492b018f3aba188b5f930327e4" FOREIGN KEY ("cargo_nivel_id") REFERENCES "cargo_nivel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" ADD CONSTRAINT "FK_596617d9cd1f2af5c3e310fe2c2" FOREIGN KEY ("created_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" ADD CONSTRAINT "FK_21d7341871f8c94212e420941a5" FOREIGN KEY ("updated_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_3f660b08d0b7c1c59edb5afa5d0" FOREIGN KEY ("asignacion_cargo_id") REFERENCES "asignacion_cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_c2c485a4c05d44b021aa101d4ac" FOREIGN KEY ("cargo_nivel_id_anterior") REFERENCES "cargo_nivel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_1fdef87d6736df79dc8e7141060" FOREIGN KEY ("cargo_nivel_id_nuevo") REFERENCES "cargo_nivel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_de8e655d09894f10462faf68e99" FOREIGN KEY ("cargo_id_anterior") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_3f56ae10c73b20587ab98614bb3" FOREIGN KEY ("cargo_id_nuevo") REFERENCES "cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_ae4673fa3bb910c29ede2599f03" FOREIGN KEY ("unidad_id_anterior") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_cf32beb0e0985e7f73797d79b0c" FOREIGN KEY ("unidad_id_nuevo") REFERENCES "unidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" ADD CONSTRAINT "FK_5e91792bfadfa68b417b2a753c6" FOREIGN KEY ("changed_by") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_5e91792bfadfa68b417b2a753c6"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_cf32beb0e0985e7f73797d79b0c"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_ae4673fa3bb910c29ede2599f03"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_3f56ae10c73b20587ab98614bb3"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_de8e655d09894f10462faf68e99"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_1fdef87d6736df79dc8e7141060"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_c2c485a4c05d44b021aa101d4ac"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo_hist" DROP CONSTRAINT "FK_3f660b08d0b7c1c59edb5afa5d0"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" DROP CONSTRAINT "FK_21d7341871f8c94212e420941a5"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" DROP CONSTRAINT "FK_596617d9cd1f2af5c3e310fe2c2"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" DROP CONSTRAINT "FK_7492b018f3aba188b5f930327e4"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" DROP CONSTRAINT "FK_b3d2a1b7617953e4ec7ad2b4404"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" DROP CONSTRAINT "FK_b3b847b97b58bd340c4148136b9"`);
        await queryRunner.query(`ALTER TABLE "asignacion_cargo" DROP CONSTRAINT "FK_9eacdb795f7702bee3d5d13f619"`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" DROP CONSTRAINT "FK_af6d351da6c6de38c178a5810e4"`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" DROP CONSTRAINT "FK_72224b7331d73d4b400374deda9"`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" DROP CONSTRAINT "FK_4372c3a2d85776b49f0be9ce9cd"`);
        await queryRunner.query(`ALTER TABLE "cargo_jerarquia_hist" DROP CONSTRAINT "FK_7c4fef8d47aad3a04af9903c691"`);
        await queryRunner.query(`ALTER TABLE "cargo_unidad" DROP CONSTRAINT "FK_b504f6ad081e70588e1603204b2"`);
        await queryRunner.query(`ALTER TABLE "cargo_unidad" DROP CONSTRAINT "FK_3587e73fd858b4b1481c365f12c"`);
        await queryRunner.query(`ALTER TABLE "cargo_nivel" DROP CONSTRAINT "FK_5236f3b0b7df382a9e31d5e8bbc"`);
        await queryRunner.query(`ALTER TABLE "cargo_nivel" DROP CONSTRAINT "FK_b49abae8123146baa3a442d85b5"`);
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_23819fac1eadcc0723ecfa776ec"`);
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_d450c004048c0d34b06c6a3ee31"`);
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_fa5bec4729251d55f99d694df35"`);
        await queryRunner.query(`ALTER TABLE "unidad_dependencia_funcional" DROP CONSTRAINT "FK_1335f38e53860a0875e4e5bb5c4"`);
        await queryRunner.query(`ALTER TABLE "unidad_dependencia_funcional" DROP CONSTRAINT "FK_1f3c749e081a5b26ea2f40d759e"`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" DROP CONSTRAINT "FK_d6f6f4e40d731848abfb6439138"`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" DROP CONSTRAINT "FK_3189e3ae4d0abc8be343e98833f"`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" DROP CONSTRAINT "FK_87c1ca734b13a8c5abbf0ee7076"`);
        await queryRunner.query(`ALTER TABLE "unidad_jerarquia_hist" DROP CONSTRAINT "FK_277ae503a43eb5a218a3b068248"`);
        await queryRunner.query(`ALTER TABLE "unidad" DROP CONSTRAINT "FK_c9ddfa456508681b5b2776b9b00"`);
        await queryRunner.query(`ALTER TABLE "unidad" DROP CONSTRAINT "FK_13a95ae8387dce63b0a542a9cdb"`);
        await queryRunner.query(`ALTER TABLE "unidad" DROP CONSTRAINT "FK_94844a42a53e0a70efd65763d35"`);
        await queryRunner.query(`ALTER TABLE "unidad" DROP CONSTRAINT "FK_5c52057af4061c6fb9baba16e12"`);
        await queryRunner.query(`ALTER TABLE "unidad" DROP CONSTRAINT "FK_ff4bf80818c0aa6e5486e1ab81d"`);
        await queryRunner.query(`ALTER TABLE "unidad" DROP CONSTRAINT "FK_347f835cad56196221bea29b572"`);
        await queryRunner.query(`ALTER TABLE "unidad" DROP CONSTRAINT "FK_10ac2cffa223556cf74dc141621"`);
        await queryRunner.query(`ALTER TABLE "unidad_relacion_interna" DROP CONSTRAINT "FK_d931058846fe3338ccf4902b4fc"`);
        await queryRunner.query(`ALTER TABLE "unidad_relacion_interna" DROP CONSTRAINT "FK_11e015ea5591f1361f29eb86bb4"`);
        await queryRunner.query(`ALTER TABLE "unidad_relacion_externa" DROP CONSTRAINT "FK_2651ddf83eab297d6c9f88250a6"`);
        await queryRunner.query(`ALTER TABLE "unidad_funcion" DROP CONSTRAINT "FK_469e4b9d573cdccb7cb117a924d"`);
        await queryRunner.query(`ALTER TABLE "auditoria_cambio" DROP CONSTRAINT "FK_071d2676e20d33907f9dfd35b18"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_1fbc7de91b8e96937ed27739e8f"`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_ac8911cd54a61461c9926541401"`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_29e9a9079c7ba01c1b301cf5555"`);
        await queryRunner.query(`DROP TABLE "asignacion_cargo_hist"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66ad3bd27dca1daec5447228d0"`);
        await queryRunner.query(`DROP TABLE "asignacion_cargo"`);
        await queryRunner.query(`DROP TABLE "cargo_jerarquia_hist"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d4c270f3561571dede3a9b181"`);
        await queryRunner.query(`DROP TABLE "cargo_unidad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5220df3d12d0ed70f587470e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d30b75f922d3ee67d6b0df7621"`);
        await queryRunner.query(`DROP TABLE "cargo_nivel"`);
        await queryRunner.query(`DROP TABLE "cargo"`);
        await queryRunner.query(`ALTER TABLE "unidad_dependencia_funcional" DROP CONSTRAINT "CHK_unidad_dependencia_diferente"`);
        await queryRunner.query(`DROP TABLE "unidad_dependencia_funcional"`);
        await queryRunner.query(`DROP TABLE "unidad_jerarquia_hist"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07cd99340fb171274e5bfed596"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_861ec82ab1c13cb0a2ee94d10a"`);
        await queryRunner.query(`DROP TABLE "unidad"`);
        await queryRunner.query(`DROP TABLE "unidad_relacion_interna"`);
        await queryRunner.query(`DROP TABLE "unidad_relacion_externa"`);
        await queryRunner.query(`DROP TABLE "unidad_funcion"`);
        await queryRunner.query(`DROP TABLE "tipo_unidad"`);
        await queryRunner.query(`DROP TABLE "catalogo_relacion"`);
        await queryRunner.query(`DROP TABLE "catalogo_nivel"`);
        await queryRunner.query(`DROP TABLE "catalogo_tipo"`);
        await queryRunner.query(`DROP TABLE "auditoria_cambio"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP TABLE "usuario_rol"`);
        await queryRunner.query(`DROP TABLE "rol"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86ae2f9d6da4482363f832340b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cd57db9cc1b133cacb180b29e"`);
        await queryRunner.query(`DROP TABLE "persona"`);
    }

}
